pub fn load_input(day: usize) -> &'static str {
    match day {
        1 => include_str!("../assets/inputs/day01.txt"),
        2 => include_str!("../assets/inputs/day02.txt"),
        3 => include_str!("../assets/inputs/day03.txt"),
        4 => include_str!("../assets/inputs/day04.txt"),
        5 => include_str!("../assets/inputs/day05.txt"),
        6 => include_str!("../assets/inputs/day06.txt"),
        7 => include_str!("../assets/inputs/day07.txt"),
        8 => include_str!("../assets/inputs/day08.txt"),
        9 => include_str!("../assets/inputs/day09.txt"),
        10 => include_str!("../assets/inputs/day10.txt"),
        11 => include_str!("../assets/inputs/day11.txt"),
        12 => include_str!("../assets/inputs/day12.txt"),
        13 => include_str!("../assets/inputs/day13.txt"),
        14 => include_str!("../assets/inputs/day14.txt"),
        15 => include_str!("../assets/inputs/day15.txt"),
        16 => include_str!("../assets/inputs/day16.txt"),
        17 => include_str!("../assets/inputs/day17.txt"),
        18 => include_str!("../assets/inputs/day18.txt"),
        19 => include_str!("../assets/inputs/day19.txt"),
        20 => include_str!("../assets/inputs/day20.txt"),
        21 => include_str!("../assets/inputs/day21.txt"),
        22 => include_str!("../assets/inputs/day22.txt"),
        23 => include_str!("../assets/inputs/day23.txt"),
        24 => include_str!("../assets/inputs/day24.txt"),
        25 => include_str!("../assets/inputs/day25.txt"),
        _ => unreachable!(),
    }
}

#[allow(unused)]
pub fn load_example(day: usize) -> &'static str {
    match day {
        1 => include_str!("../assets/examples/day01.txt"),
        2 => include_str!("../assets/examples/day02.txt"),
        3 => include_str!("../assets/examples/day03.txt"),
        4 => include_str!("../assets/examples/day04.txt"),
        5 => include_str!("../assets/examples/day05.txt"),
        6 => include_str!("../assets/examples/day06.txt"),
        7 => include_str!("../assets/examples/day07.txt"),
        8 => include_str!("../assets/examples/day08.txt"),
        9 => include_str!("../assets/examples/day09.txt"),
        10 => include_str!("../assets/examples/day10.txt"),
        11 => include_str!("../assets/examples/day11.txt"),
        12 => include_str!("../assets/examples/day12.txt"),
        13 => include_str!("../assets/examples/day13.txt"),
        14 => include_str!("../assets/examples/day14.txt"),
        15 => include_str!("../assets/examples/day15.txt"),
        16 => include_str!("../assets/examples/day16.txt"),
        17 => include_str!("../assets/examples/day17.txt"),
        18 => include_str!("../assets/examples/day18.txt"),
        19 => include_str!("../assets/examples/day19.txt"),
        20 => include_str!("../assets/examples/day20.txt"),
        21 => include_str!("../assets/examples/day21.txt"),
        22 => include_str!("../assets/examples/day22.txt"),
        23 => include_str!("../assets/examples/day23.txt"),
        24 => include_str!("../assets/examples/day24.txt"),
        25 => include_str!("../assets/examples/day25.txt"),
        _ => unreachable!(),
    }
}
